# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
# 手动运行
  workflow_dispatch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
#      - name: 设置.NET环境
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: 6.0.x
#      - name: 还原Nuget包
#        run: dotnet restore
#      - name: 编译
#        run: dotnet build --no-restore
#      - name: 测试
#        run: dotnet test --no-build --verbosity normal
#      - name: 查看当前目录
#        run: echo $(pwd)
#      - name: 查看当前目录列表
#        run: echo $(ls -ll)
#      - name: 编译docker镜像
#        run: docker build . --file DotnetCoreMvcTestGithubActions/Dockerfile --tag my-image-name:$(date +%s)
#      - name: 保存docker镜像
#        run: docker save -o /my-image-name-$(date +%s).tar my-image-name:$(date +%s) 
      - name: 编译docker镜像
        run: docker build . --file DotnetCoreMvcTestGithubActions/Dockerfile --tag ${{secrets.DOCKER_HUB_USERNAME}}/my-image-name:1
      - name: 登录Docker Hub
        run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
      - name: 推送镜像
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/my-image-name:1
      - name: 退出登录
        run: docker logout
      # - name: 保存docker镜像
      #   run: docker save -o my-image-name-1.tar my-image-name:1
      # - name: 上传制品
      #   uses: actions/upload-artifact@v3
      #   with: 
      #     name: docker-image-file
      #     path: /home/runner/work/actions/actions/my-image-name-1.tar